services:
  - type: web
    name: bullrun-stats-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: VITE_API_URL
        value: https://bullrun-stats-backend.onrender.com

  - type: web
    name: bullrun-stats-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 